### ISSUE TITLE
Nefunkční cyklus for-each

### ISSUE THREAD

**Issue by zabak79** [PoloShock/psdiagram#6]
Dobrý den,
   pokuším se vytvořit si nějaké pole a to následně vypsat, ale při výpisu pole pomocí for-each se příklad zacyklí. Přikladám alogoritmus, který jsem zazipoval. Jako vstupní hodnoty používám počet prvků _N_=5, prvky _pole_  [1,2,1,2,1]. Snažím se je nacpat jako text do proměnné _seznam_ a tu pak vypsat. Díky zacyklení ve for-each se ale výpis nezdaří.
[priklad.zip](https://github.com/PoloShock/psdiagram/files/6162941/priklad.zip)

**Comment by PoloShock** [comment]
Nevěřím vlastním očím, máte pravdu. Algoritmus se zacyklí, i když by neměl. 
Mockrát děkuji za nahlášení, toto budu muset urychleně opravit. :-)

**Comment by zabak79** [comment]
Jen pro zajímavost, pokud zadám do pole řetězce ["Petr","Pavel","Eva","Iva","Ivan"], pak vše funguje. V proměnné _seznam_ je řetězec "Petr,Pavel,Eva,Iva,Ivan". Problém bude asi někde s tím číselným polem?

**Comment by PoloShock** [comment]
Opraveno ve verzi 1.4.4.2.
